name: 'ReadmeRank Action'
description: 'Automated GitHub Action to evaluate, score, and optimize README files.'
author: 'am9'

inputs:
  github_token:
    description: 'GitHub token to access the repository'
    required: false
    default: '${{ github.token }}'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Run ReadmeRank Analyzer
      run: python ${{ github.action_path }}/main.py
      shell: bash
      
